#!/usr/bin/python

import os
import argparse
from launcher.finder import Finder

## Starting raiden launcher
parser = argparse.ArgumentParser()
parser.add_argument("action", help="Define launcher action, can be start, stop, restart, delete")
parser.add_argument("--platform", help="Define the platform folder path")
parser.add_argument("--applications", help="Define the application folder path")
arguments = parser.parse_args()

## setting the raiden root path
## And initializing finder with it
raiden_path = os.path.dirname(os.path.realpath(__file__))
finder = Finder(raiden_path)

## @next -> adding setters
## Checking if user want to override some paths
# if arguments.platform_path:
# 	finder.platform_path = arguments.platform_path
# if arguments.applications_path:
# 	finder.applications_path = arguments.applications_path

finder.search()

## Launch docker collections
## - First the platform
## - And then applications
##
## And before each launching we must check if image is built